kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: my-namespace
subjects:
  - kind: ServiceAccount
    name: spring-security
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""