metadata:
  annotations:
    configmap.jkube.io/update-on-change: ${project.artifactId}
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: ${project.artifactId}
      containers:
        - volumeMounts:
            - name: config
              mountPath: /deployments/config
          env:
            - name: TZ
              value: Asia/Shanghai
      serviceAccount: spring